# Generated by Django 5.1.3 on 2025-02-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_match_sport_alter_player_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_sport',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='type_voluntary',
            field=models.IntegerField(choices=[(0, 'Voluntario'), (1, 'Organização'), (2, 'Técnico')], default=0),
        ),
    ]
