# Generated by Django 5.1.3 on 2025-03-13 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_team_sport_status_alter_voluntary_type_voluntary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=500)),
                ('contend', models.CharField(max_length=1500)),
                ('bolletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bolletin')),
            ],
        ),
    ]
