# Generated by Django 5.1.3 on 2025-03-15 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_bolletin_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_team_sport',
            name='team_sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.team_sport'),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='type_voluntary',
            field=models.IntegerField(choices=[(0, 'Voluntario'), (1, 'Organização'), (2, 'Técnico'), (3, 'Chefe de delegação')], default=0),
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('file', models.ImageField(blank=True, upload_to='attachments/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
