# Generated by Django 5.1.3 on 2025-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rg',
            field=models.FileField(default=1, upload_to='rg/'),
            preserve_default=False,
        ),
    ]
