# Generated by Django 5.1.3 on 2025-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_terms_use_options_terms_use_accepted_and_more.py'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rg',
            field=models.FileField(default=1, upload_to='rg/'),
            preserve_default=False,
        ),
    ]
