# Generated by Django 5.1.3 on 2025-04-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_terms_use_options_terms_use_accepted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms_use',
            options={},
        ),
        migrations.RemoveField(
            model_name='terms_use',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='terms_use',
            name='document',
        ),
        migrations.RemoveField(
            model_name='terms_use',
            name='name',
        ),
        migrations.RemoveField(
            model_name='terms_use',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='terms_use',
            name='siape',
        ),
    ]
