# Generated by Django 5.1.3 on 2025-04-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_player_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntary',
            name='type_voluntary',
            field=models.IntegerField(choices=[(0, 'Voluntario'), (1, 'Técnico'), (2, 'Organização'), (3, 'Estagiario'), (4, 'Chefe de delegação')], default=0),
        ),
    ]
