# Generated by Django 5.1.3 on 2025-04-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_player_rg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms_use',
            options={'verbose_name': 'Terms_Use', 'verbose_name_plural': 'Terms_uses'},
        ),
        migrations.RemoveField(
            model_name='terms_use',
            name='date_accept',
        ),
        migrations.AddField(
            model_name='terms_use',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terms_use',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms_use',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='document_boss/'),
        ),
        migrations.AddField(
            model_name='terms_use',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='terms_use',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo_boss/'),
        ),
        migrations.AddField(
            model_name='terms_use',
            name='siape',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
