# Generated by Django 5.1.3 on 2025-04-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_terms_use_options_remove_player_rg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms_use',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='terms_use',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, '100 M'), (7, 'Salto em distância'), (8, 'Lançamento de dardo'), (9, 'Arremesso de peso')]),
        ),
        migrations.AlterField(
            model_name='team_sport',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, '100 M'), (7, 'Salto em distância'), (8, 'Lançamento de dardo'), (9, 'Arremesso de peso')]),
        ),
    ]
