# Generated by Django 5.1.3 on 2025-05-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_statement_statement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntary',
            name='type_voluntary',
            field=models.IntegerField(choices=[(0, 'Voluntário'), (1, 'Técnico de modalidade esportiva'), (2, 'Apoio'), (3, 'Estagiário'), (4, 'Chefe de delegação')], default=0),
        ),
    ]
