# Generated by Django 5.1.3 on 2025-07-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_voluntary_type_voluntary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
